// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {netvisor} from '../models';

export function AddEndpoint(arg1:core.Endpoint):Promise<void>;

export function DeleteEndpoint(arg1:string):Promise<void>;

export function ExportResults(arg1:string,arg2:Array<core.APIQueryRecord>):Promise<string>;

export function GetAPICatalog():Promise<core.APICatalog>;

export function GetDeviceInventory():Promise<Array<core.DeviceInventory>>;

export function GetEndpoints():Promise<Array<core.Endpoint>>;

export function GetEndpointsByService(arg1:string):Promise<Record<string, core.APIDefinition>>;

export function GetNetVisorAPIs():Promise<Array<netvisor.APIDefinition>>;

export function GetNetVisorAPIsByService(arg1:string):Promise<Array<netvisor.APIDefinition>>;

export function GetNetVisorTables():Promise<Array<string>>;

export function GetQueryLog():Promise<Array<core.APIQueryRecord>>;

export function RunAPIRequest(arg1:core.ExplorerRequest):Promise<core.ExplorerResponse>;

export function SearchEndpoints(arg1:string):Promise<Array<core.APIDefinition>>;

export function SearchNetVisorAPIs(arg1:string):Promise<Array<netvisor.APIDefinition>>;

export function ServeAPICatalog():Promise<Record<string, any>>;

export function ServeDeviceInventory():Promise<Array<core.DeviceInventory>>;

export function TestAPIConnection(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<Record<string, any>>;

export function TestConnection(arg1:string):Promise<core.ConnectionTestResult>;

export function UpdateEndpoint(arg1:core.Endpoint):Promise<void>;
