// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEndpoint(arg1) {
  return window['go']['main']['App']['AddEndpoint'](arg1);
}

export function DeleteEndpoint(arg1) {
  return window['go']['main']['App']['DeleteEndpoint'](arg1);
}

export function ExportResults(arg1, arg2) {
  return window['go']['main']['App']['ExportResults'](arg1, arg2);
}

export function GetAPICatalog() {
  return window['go']['main']['App']['GetAPICatalog']();
}

export function GetDeviceInventory() {
  return window['go']['main']['App']['GetDeviceInventory']();
}

export function GetEndpoints() {
  return window['go']['main']['App']['GetEndpoints']();
}

export function GetEndpointsByService(arg1) {
  return window['go']['main']['App']['GetEndpointsByService'](arg1);
}

export function GetNetVisorAPIs() {
  return window['go']['main']['App']['GetNetVisorAPIs']();
}

export function GetNetVisorAPIsByService(arg1) {
  return window['go']['main']['App']['GetNetVisorAPIsByService'](arg1);
}

export function GetNetVisorTables() {
  return window['go']['main']['App']['GetNetVisorTables']();
}

export function GetQueryLog() {
  return window['go']['main']['App']['GetQueryLog']();
}

export function RunAPIRequest(arg1) {
  return window['go']['main']['App']['RunAPIRequest'](arg1);
}

export function SearchEndpoints(arg1) {
  return window['go']['main']['App']['SearchEndpoints'](arg1);
}

export function SearchNetVisorAPIs(arg1) {
  return window['go']['main']['App']['SearchNetVisorAPIs'](arg1);
}

export function ServeAPICatalog() {
  return window['go']['main']['App']['ServeAPICatalog']();
}

export function ServeDeviceInventory() {
  return window['go']['main']['App']['ServeDeviceInventory']();
}

export function TestAPIConnection(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TestAPIConnection'](arg1, arg2, arg3, arg4, arg5);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UpdateEndpoint(arg1) {
  return window['go']['main']['App']['UpdateEndpoint'](arg1);
}
